version: '3.5'

services:
  cims-dev:
    build:
      context: .
      dockerfile: dockerfile-dev
    container_name: cims-dev
    environment:
      DJANGO_DEBUG: 1
    volumes:
      - .db_data:/usr/src/cims/.db
      - ./media:/usr/src/cims/media
      - ./migrations_staff:/usr/src/cims/staff/migrations
      - ./migrations_inventory:/usr/src/cims/inventory/migrations
    ports:
      - "8001:8000"
