version: '3.5'

services:
  cims:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cims
    volumes:
      - .db_data:/usr/src/cims/.db
      - ./migrations_staff:/usr/src/cims/staff/migrations
      - ./migrations_inventory:/usr/src/cims/inventory/migrations
    ports:
      - "8001:8000"